# Naive Gauss Elimination (step by step)

<hr style="border: 4px solid;">
Consider we want to solve this system of linear equations;

$$ 
\begin{align*}
2x + y - 3z &= 4 \\
-x + 2y - z &= 3 \\
4x - 3y + 2z &= 1
\end{align*}
$$

We can write this system of linear equations in matrix form as:
$$ \begin{bmatrix} 2 & 1 & -3 \\ -1 & 2 & -1 \\ 4 & -3 & 2 \end{bmatrix} \begin{bmatrix} x \\ y \\ z \end{bmatrix} = \begin{bmatrix} 4 \\ 3 \\ 1 \end{bmatrix} $$


<hr style="border: 2px solid;">
1. &emsp; $ \mbox{Preparation} $

&emsp;&emsp; a.) &emsp; Importing library needed for the code

In [1]:
import numpy as np

<hr>
&emsp;&emsp; b.) &emsp; Generating matrices

In [2]:
A = np.array([
    [2,1,-3],
    [-1,2,-1],
    [4,-3,2]
])
print(A)

[[ 2  1 -3]
 [-1  2 -1]
 [ 4 -3  2]]


In [3]:
b = np.array([
    [4.0],
    [3.0],
    [1.0]
])
print(b)

[[4.]
 [3.]
 [1.]]


<hr>
&emsp;&emsp; c.) &emsp; Building augmented matrices of <br>

$$ \left[ \begin{array}{ccc|c} 2 & 1 & -3 & 4 \\ -1 & 2 & -1 & 3 \\ 4 & -3 & 2 & 1 \end{array} \right] $$
$$ $$

In [5]:
aug = np.hstack((A,b))
print(aug)

[[ 2.  1. -3.  4.]
 [-1.  2. -1.  3.]
 [ 4. -3.  2.  1.]]


<hr style="border: 2px solid;">
2. &emsp; $ \mbox{Forward Elimination} $

&emsp;&emsp; a.) &emsp; Eliminating the first column on the second row (R1) using the first row (R0) <br>

$$ R_1 - \frac{a_{10}}{a_{00}}R_0 \rightarrow R'_1 $$

In [6]:
scale = aug[1,0]/aug[0,0]
aug[1] = aug[1] - scale*aug[0]
print(aug)

[[ 2.   1.  -3.   4. ]
 [ 0.   2.5 -2.5  5. ]
 [ 4.  -3.   2.   1. ]]


<hr>
&emsp;&emsp; b.) &emsp; Eliminating the first column on the third row (R2) using the first row (R0) <br>

$$ R_2 - \frac{a_{20}}{a_{00}}R_0 \rightarrow R'_2 $$

<hr>
&emsp;&emsp; c.) &emsp; Eliminating the second column on the third row (R'2) using the second row (R'1) <br>

$$ R'_2 - \frac{a'_{21}}{a'_{11}}R'_1 \rightarrow R''_2 $$

In [11]:
scale = aug[2,0]/aug[0,0]
aug[2] = aug[2] - scale*aug[0]
print(aug)

[[ 2.   1.  -3.   4. ]
 [ 0.   2.5 -2.5  5. ]
 [ 0.  -5.   8.  -7. ]]


In [12]:
scale = aug[2,1]/aug[1,1]
aug[2] = aug[2] - scale*aug[1]
print(aug)

[[ 2.   1.  -3.   4. ]
 [ 0.   2.5 -2.5  5. ]
 [ 0.   0.   3.   3. ]]


<hr style="border: 2px solid;">
3. &emsp; $ \mbox{Back Substitution} $

&emsp;&emsp; a.) &emsp; From the last row ($R''_2$), solve for $z$ <br>

$$ a''_{22}z = a''_{23} \rightarrow z = \frac{a''_{23}}{a''_{22}}$$

In [19]:
z = aug[2,3]/aug[2,2]
print("z = {}".format(z))

z = 1.0


<hr>
&emsp;&emsp; b.) &emsp; From the second row ($R'_1$), solve for $y$ <br>

$$ a'_{11}y + a'_{12}z = a'_{13} \rightarrow y = \frac{a'_{13} - a'_{12}z}{a'_{11}} $$

In [20]:
y = (aug[1,3] - aug[1,2]*z)/aug[1,1]
print("y = {}".format(y))

y = 3.0


<hr>
&emsp;&emsp; c.) &emsp; From the first row ($R_0$), solve for $x$ <br>

$$ a_{00}x + a_{01}y + a_{02}z = a_{03} \rightarrow x = \frac{a_{03} - (a_{01}y + a_{02}z)}{a_{00}} $$

In [21]:
x = (aug[0,3] - (aug[0,1]*y + aug[0,2]*z))/(aug[0,0])
print("x = {}".format(x))

x = 2.0
