# Naive Gauss Elimination (optimized)

<hr style="border: 4px solid;">
Consider we want to solve this system of linear equations;

$$ 
\begin{align*}
2x + y - 3z &= 4 \\
-x + 2y - z &= 3 \\
4x - 3y + 2z &= 1
\end{align*}
$$

We can write this system of linear equations in matrix form as:
$$ \begin{bmatrix} 2 & 1 & -3 \\ -1 & 2 & -1 \\ 4 & -3 & 2 \end{bmatrix} \begin{bmatrix} x \\ y \\ z \end{bmatrix} = \begin{bmatrix} 4 \\ 3 \\ 1 \end{bmatrix} $$


<hr style="border: 2px solid;">
1. &emsp; $ \mbox{Preparation} $

&emsp;&emsp; a.) &emsp; Importing library needed for the code

In [1]:
import numpy as np

<hr>
&emsp;&emsp; b.) &emsp; Generating matrices

In [2]:
A = np.array([[2,1,-3],[-1,2,-1],[4,-3,2]])
print(A)

[[ 2  1 -3]
 [-1  2 -1]
 [ 4 -3  2]]


In [3]:
b = np.array([[4.0],[3.0],[1.0]])
print(b)

[[4.]
 [3.]
 [1.]]


<hr>
&emsp;&emsp; c.) &emsp; Building augmented matrices of <br>

$$ \left[ \begin{array}{ccc|c} 2 & 1 & -3 & 4 \\ -1 & 2 & -1 & 3 \\ 4 & -3 & 2 & 1 \end{array} \right] $$
$$ $$

In [5]:
aug = np.hstack((A,b))
print(aug)

[[ 2.  1. -3.  4.]
 [-1.  2. -1.  3.]
 [ 4. -3.  2.  1.]]


<hr style="border: 2px solid;">
2. &emsp; $ \mbox{Forward Elimination} $

&emsp;&emsp; Eliminating the lower diagonal elements <br>

$$ \left[ \begin{array}{ccc|c} a_{00} & a_{01} & a_{02} & a_{03} \\ a_{10} & a_{11} & a_{12} & a_{13} \\ a_{20} & a_{21} & a_{22} & a_{23} \end{array} \right] 
\rightarrow
\left[ \begin{array}{ccc|c} a_{00} & a_{01} & a_{02} & a_{03} \\ 0 & a'_{11} & a'_{12} & a'_{13} \\ 0 & 0 & a''_{22} & a''_{23} \end{array} \right] $$

In [6]:
n = len(b)
for i in range(n):
    for j in range(i+1,n):
        scale = aug[j,i]/aug[i,i]
        aug[j] = aug[j] - scale*aug[i]

print(aug)

[[ 2.   1.  -3.   4. ]
 [ 0.   2.5 -2.5  5. ]
 [ 0.   0.   3.   3. ]]


<hr style="border: 2px solid;">
3. &emsp; $ \mbox{Back Substitution} $


&emsp;&emsp; Solving for each variables

$$ \begin{bmatrix} a_{00} & a_{01} & a_{02} \\ 0 & a'_{11} & a'_{12} \\ 0 & 0 & a''_{22} \end{bmatrix} 
\begin{bmatrix} x \\ y \\ z \end{bmatrix} = \begin{bmatrix} a_{03} \\ a'_{13} \\ a''_{23} \end{bmatrix} \rightarrow 
\left\{\begin{align*} a_{00}x + a_{01}y + a_{02}z = a_{03} \\ a'_{11}y + a'_{12}z = a'_{13} \\ a''_{22}z = a''_{23} \end{align*}\right\} $$
$$ \rightarrow z = \frac{a''_{23}}{a''_{22}}; y = \frac{a'_{13} - a'_{12}z}{a'_{11}}; x = \frac{a_{03} - (a_{01}y + a_{02}z)}{a_{00}}.$$

In [7]:
x = np.zeros(n)
for i in range(n-1, -1, -1):
    x[i] = (aug[i,n] - np.dot(aug[i,i:n], x[i:n])) / aug[i,i]

print("x = {}".format(x[0]))
print("y = {}".format(x[1]))
print("z = {}".format(x[2]))

x = 2.0
y = 3.0
z = 1.0
